version: '3'
services:
  strapi-server:
    build:
      context: ./strapi-server
    container_name: strapi-server
    image: strapi:latest
    restart: unless-stopped
    env_file: ./strapi-server/.env
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=strapi-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_SSL=false
    ports:
      - 1337:1337
    volumes:
      - ./strapi-server/config:/opt/app/config
      - ./strapi-server/src:/opt/app/src
      - ./strapi-server/package.json:/opt/package.json
      - ./strapi-server/yarn.lock:/opt/yarn.lock
      - ./strapi-server/.env:/opt/app/.env
      - ./strapi-server/public/uploads:/opt/app/public/uploads
    depends_on:
      - strapi-db

  strapi-db:
    container_name: strapi-db
    image: mysql:latest
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ./__docker/__strapidb:/var/lib/mysql
      - ./__sql:/tmp/backups
